language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -r requirements_analyses.txt"
 - "pip install python-coveralls coverage"
script: "travis_retry python setup.py nosetests --with-coverage --cover-package=databench"
after_success:
  - coveralls
